---
title: Combineer tekst en variabelen
hero_image: images/banner.png
description: Combineer tekst en variabelen in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Combineer tekst en variabelen in JavaScript
