title: Combine text and variables
hero_image: images/banner.png
description: Combine text and variables in JavaScript
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Combine text and variables in JavaScript
